### ISSUE TITLE
Issue with imports in required scripts

### ISSUE THREAD

**Issue by ghost** [webdiscus/pug-plugin#91] opened 2023-11-27 16:09 UTC
I posted this issue in the webpack repo but I was wondering if this has something to do with the PugPlugin, any clue?

Original text from https://github.com/webpack/webpack/issues/17832

> When I start webpack in watch mode the first time it compiles everything goes fine but when I try to edit an imported module in a script I use in one of my templates I get a strange error in console and in the browser overlay.
> When I edit an imported module (external file) webpack shouldn't show any errors and just trigger a reload.

**Comment by webdiscus** [comment] 2023-11-27 16:29
Hello @racc-ode,

please close the [issue](https://github.com/webpack/webpack/issues/17832) by Webpack, because you use the Pug Plugin.
Can you please create a small repo with reproducible issue, then I can help you.

**Comment by racc-ode** [comment] 2023-11-27 21:19
Sure @webdiscus, thanks mate.

It isn't a critical problem, only slows down a bit development.

I appreciate it, good job with the plugin and thanks again!

**Comment by webdiscus** [comment] 2023-11-28 13:55
@racc-ode 

I have tested this use case with [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin/tree/master/test/manual/watch-dependencies-import-js) . After changes in the imported JS file, It works w/o error.
Therefore, this issue will be fixed in the next  major version `v5`, because the code base of the next version will be switched on the bundler plugin to improve the pug plugin.

**Comment by webdiscus** [comment] 2024-03-08 22:54
@racc-ode

the new pug plugin `v5.0.0` is released and based on the [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin)

The issuer should be fixed automatically with the release `v5.0.0`.

**Closed by webdiscus** 2024-03-08 22:54 UTC
Labels: bug
