### ISSUE TITLE
How to complie the pug file to template function on pug-plugin v5 like pug-plugin v4?

### ISSUE THREAD

**Issue by yingziwu** [webdiscus/pug-plugin#105] opened 2024-03-19 13:29 UTC
[My project](https://github.com/404-novel-project/novel-downloader/tree/develop) use the `PugPlugin.loader`  complie the pug file that imported from ts file to template function, but after upgrade  pug-plugin from v4 to v5, I found that only add `PugPlugin.loader`  to `rules` don't work and report  `TypeError: Cannot read properties of undefined (reading 'getHooks')`.

I try to do the migration as [5.0.0 changelog](https://github.com/webdiscus/pug-plugin/blob/master/CHANGELOG.md#500-2024-02-08), but it don't work as my expectation.

-------

**Step to reproduce**

1. Clone the repo

```bash
git clone https://github.com/404-novel-project/novel-downloader.git
```

2. Build on pug-plugin v4

```bash
git checkout f5bb8769a5fb507ec6e18d4f8e9f244fa2df3dbf
yarn install
yarn webpack build --mode development -c webpack/backgroud.*.config.js
```

![pug-plugin v4](https://github.com/webdiscus/pug-plugin/assets/22741471/d8db56e1-04c7-46bb-9c61-8dcff0556d49)

The pug-plugin v4 work normally.

3. Build on  pug-plugin v5

```bash
git checkout bcc75903052a7cfdeb094d3695af4b01512e61fa
yarn install
rm -r dist
yarn webpack build --mode development -c webpack/backgroud.*.config.js
```

build failed and get error:

```
ERROR in ./src/backgroud/models/saver/epub/pug/content.opf.pug
Module build failed (from ./node_modules/html-bundler-webpack-plugin/src/Loader/index.js):
TypeError: Cannot read properties of undefined (reading 'getHooks')
    at PluginService.getHooks (/tmp/novel-downloader/node_modules/html-bundler-webpack-plugin/src/Plugin/PluginService.js:111:24)
    at Object.loader (/tmp/novel-downloader/node_modules/html-bundler-webpack-plugin/src/Loader/index.js:27:31)
 @ ./src/backgroud/index.ts 5:0-70 6:12-19
```

4. do the migration as 5.0.0 changelog

https://github.com/404-novel-project/novel-downloader/commit/38ad1e3e4fec1eef08177d843f38afb0701cb380

```bash
git checkout 38ad1e3e4fec1eef08177d843f38afb0701cb380
yarn install
rm -r dist
yarn webpack build --mode development -c webpack/backgroud.*.config.js
```

![pug-plugin v5](https://github.com/webdiscus/pug-plugin/assets/22741471/9cec092d-c385-4d2d-822d-916873df9b26)

Only output `dist/chromium/backgroud/bundle.js` and **`dist/firefox/backgroud/bundle.js` disappear**.

--------------

I have readed the document of [pug-plugin](https://github.com/webdiscus/pug-plugin) and [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin), but not found how to resolve this problem.

**Comment by webdiscus** [comment] 2024-03-19 14:31
@yingziwu 

yes, I can reproduce the problem: the second build process does not generate the `bundle.js` file when used the command:
```
yarn webpack build --mode development -c webpack/backgroud.*.config.js
```

## Solution
Run webpack process for each config separately.

The command generate the file `dist/chromium/backgroud/bundle.js`:
```
yarn webpack build --mode development -c webpack/backgroud.chromium.config.js
``` 

The command generate the file `dist/firefox/backgroud/bundle.js`:
```
yarn webpack build --mode development -c webpack/backgroud.firefox.config.js
```

## Note

The new Pug Plugin `v5` has absolutely new code base.

The big difference v4 vs v5:
- v4 - you can use the `PugPlugin.loader` separately, without `new PugPlugin` instance.
- v5 - you can't use `PugPlugin.loader` without the `new PugPlugin` instance, because it make no sense. The Pug Plugin is a complete solution.

The  Pug Plugin v5 use the caching of generated files. In your case you use the same source file for various output bundles. Therefore 2nd processing of the same file in the same Webpack instance will be ignored.

> This is no issue of the Pug Plugin, this is a feature of the plugin.

**Comment by yingziwu** [comment] 2024-03-19 16:44
Thanks for your reply.

> Run webpack process for each config separately.

Oh, no.
Is there better method ?
My browser plugin project has 8 webpack config (backgrourd scripts, content scripts, pages, ohter) and now I use `webpack build -c webpack/*.config.js`  build them once. 
Run webpack process for each config is too much trouble.

> The Pug Plugin v5 use the caching of generated files. In your case you use the same source file for various output bundles. Therefore 2nd processing of the same file in the same Webpack instance will be ignored.

>> The current version works stable with cache.type as 'memory' (Webpack's default setting).
>> Support for the 'filesystem' cache type is experimental and under development.

I noticed that the other plug-ins[1] used in my webpack are completely normal in the case of cache.type memory.
When using `webpack watch --mode development -c webpack/*.config.js`, after compiling for the first time, it can quickly update later. At the same time, there is no problem of ignoring the output file.

Can pug-plugin fix this problem?
Or are there any configuration options to prohibit such caching behavior.

[1] html-webpack-plugin, unplugin-auto-import, unplugin-vue-router, unplugin-vue-components

**Comment by webdiscus** [comment] 2024-03-20 09:16
> Run webpack process for each config is too much trouble.
> Can pug-plugin fix this problem?

you're right, I'll try to fix this so that the plugin can work in multi-configuration mode

**Comment by yingziwu** [comment] 2024-03-20 11:53
> Please switch from pug-plugin to [@webdiscus/pug-loader](https://github.com/webdiscus/pug-loader).

Thanks for your advise and I have switched to `@webdiscus/pug-loader`.

Besides, the webpack has a little bug, the `mode` should on `options` inside.

```javascript
module: {
  rules: [
    {
      test: /\.pug$/,
      loader: "@webdiscus/pug-loader",
      options: {
        mode: "compile",
      },
    },
  ],
},
```

**Comment by webdiscus** [comment] 2024-03-20 14:41
@yingziwu

can you please help me to find the documentation about using of the multiple config files.
Here is official documentation: [Build source using a configuration file](https://webpack.js.org/api/cli/#config).

```
npx webpack --config example.config.js
```

Your usage:
```
yarn webpack build -c *.config.js
```

is equivalent to, e.g.:
```
yarn webpack build -c app1.config.js app2.config.js
```

But I can't find this syntax anywhere.

Wenn I use with the `npm`, then this doesn't works:
```
npm webpack build -c *.config.js
- OR -
npm webpack build -c app1.config.js app2.config.js
```
because will be always used last config file only.

## Questions

1. is this  multiple config files syntax legal?
2. where can I read official documentation for this syntax?

**Comment by webdiscus** [comment] 2024-03-20 15:16
@yingziwu 

## Here is an example

Demo project files:
```
src/main.js // test JS file
base.js // base webpack config
app1.config.js // webpack config for app1
app2.config.js // webpack config for app2
```

_base.js_
```js
const path = require('path');

class DemoPlugin {
  constructor() {
    console.log('*** new Plugin()');
  }

  apply(compiler) {
    console.log('*** apply');

    compiler.hooks.thisCompilation.tap('demo-plugin', (compilation) => {
      console.log('--> thisCompilation', {
        outputPath: compilation.options.output.path, // => output always last config
      });
    });
  }
}

const config = {
  output: {
    path: path.join(__dirname, 'dist/'),
  },
  entry: {
    index: './src//main.js',
  },
  plugins: [
    new DemoPlugin(),
  ],
};

module.exports = (dirname) => {
  config.output.path = path.join(__dirname, 'dist', dirname);

  console.log(config.output.path);

  return config;
};
```

_app1.config.js_
```js
const baseConfig = require('./base');
module.exports = baseConfig('app1');
```

_app2.config.js_
```js
const baseConfig = require('./base');
module.exports = baseConfig('app2');
```

## Build

Run the command:
```
yarn webpack -c *.config.js 
```

Output in console:
```
*** new Plugin()
*** apply
*** apply
--> thisCompilation {
  outputPath: '/path/to/demo/dist/app2'
}
--> thisCompilation {
  outputPath: '/path/to/demo/dist/app2'
}
```

As you see, will be applied only last config in all compilations.
I don't understand how it should works in your project. Where is a magic?

**Comment by yingziwu** [comment] 2024-03-20 15:38
> 1. is this multiple config files syntax legal?

Yes.

> 2. where can I read official documentation for this syntax?

The flag `--config, -c` allow input the array of string.
And multiple `--config, -c` flag, just like `webpack --config webpack1.config.js --config webpack2.config.js` , is also support. 

You can read the webpack document about webpack-cli.

https://webpack.js.org/api/cli/#flags

![webpack-cli flag](https://github.com/webdiscus/pug-plugin/assets/22741471/0fd72f0f-9b9a-46c4-b7da-5efbb13b1944)


If you want, you can read the [source code](https://github.com/webpack/webpack-cli/blob/fc9f1d1c251e942220fe774c18fdbe19c4010266/packages/webpack-cli/src/webpack-cli.ts#L1930) of webpack-cli and the [test case](https://github.com/webpack/webpack-cli/blob/fc9f1d1c251e942220fe774c18fdbe19c4010266/test/build/config/multiple/multiple-config.test.js).

**Comment by webdiscus** [comment] 2024-03-20 22:49
I'm sorry, but adding the support for multiple config files is impossible for this plugin, because the `compiler.hooks.entryOption.tap` works in multi config not properly:

```js
apply(compiler) {
  compiler.hooks.entryOption.tap(pluginName, (context, entry) => {
    console.log(entry); // => is always the entipoints from last config, this is the problem
    // save entries to compilation ...
  });
}
```

Currently I don't know a solution. May be the plugin must be total new rewritten.
Also I close the issue as **not resolvable** for multi config.

**Closed by webdiscus** 2024-03-20 22:49 UTC
Labels: question, wontfix
