### ISSUE TITLE
Supports responsive-loader

### ISSUE THREAD

**Issue by mybardaklar** [webdiscus/pug-plugin#8] opened 2022-04-14 16:51 UTC
There are a lot of hmr problems. Do you still update the repo?

**Comment by webdiscus** [comment] 2022-04-14 17:26
Hello @myasarbardaklar,

thank you for the report. 
I know, after a major update to version 2, there was a problem with the webpack server and  watch.
The version 2 has new mega feature: require js script directly in pug w/o to define them in webpack entry.

I'm fixing the problems now. A fix will be released this coming weekend.
Currently you can use last 1.x.x version for webpack server and  watch.

**Comment by myasarbardaklar** [comment] 2022-04-14 18:00
Not HMR problems, there are also pug require problems. I require scss, js and image files in my pug files. I have 2 pug files. index.pug and about.pug but there are errors. I dont wanna define scss, js and image files in the webpack entry. This plugin doesnt also work with "responsive-loader" package for images. I wait your answer. Thank you so much! :)

**Comment by webdiscus** [comment] 2022-04-14 18:06
Can you please create a simple repo with reproducible issue?

**Comment by myasarbardaklar** [comment] 2022-04-14 20:38
Of course. I will do and I will share with you.

**Comment by myasarbardaklar** [comment] 2022-04-15 10:39
https://github.com/myasarbardaklar/webdiscus_pug_plugin this is the repo i created for what i wanna do with your plugin. I'll be glad if you really help me about this. Thank you so much! :)

**Comment by webdiscus** [comment] 2022-04-15 14:50
Hello @myasarbardaklar,

I can reproduce the build issues and I have fixed many problems by me local.
Some problems are in webpack config. Today later I  publish  a beta version for you.

**Comment by myasarbardaklar** [comment] 2022-04-15 15:45
Thank you so much, did you check my repo? Because im having problems. I will wait your answer. Again, thank you so much.

**Comment by webdiscus** [comment] 2022-04-16 11:55
Hello @myasarbardaklar,

I have created new experimental npm package version `2.1.0-alpha.0` with basic support the responsive-loader in pug-plugin.
Please see my commentaries in code. I opened the [PR](https://github.com/myasarbardaklar/webdiscus_pug_plugin/pull/1).

Know issues:
- by serv or watch first build is ok, but after changes and rebuild required js asset is missing. It will be fixed in next ver. \
  each time, after changes,  the webpack serv  should be restarted

The result of `responsive-loader` contains an object with `src`, `srcSet`, `placeholder`, `width`, etc.
This object is available in JS context only. But in `pug-loader` the result of  `responsive-loader` is not available, it's yet too early. In `pug-loader` (rendering Pug -> HTML) is resolved source files of required resources.
The `pug-plugin` can resolve asset filenames (public output files) by source filenames. At this stage the `pug-plugin` has access to the result of  `responsive-loader`. To extract concrete property, you can use resource query parameter `prop=PROPERTY_NAME`, where `PROPERTY_NAME` is a property name of the `responsive-loader` result.

Note: the query parameter `prop` is the universal feature of `pug-plugin`, not of the `responsive-loader`.

## Examples of using images processed by `responsive-loader`

Note:
- `./src/` is source path of images
- `/images/` is public path of processed assets

### require single image with fixed size
```pug
img(src=require('./img/logo.jpg?size=640'))
```
```html
<img src="/images/logo-640w.webp">
```

### require property `srcSet` from  result of `responsive-loader`
```pug
img(srcset=require('./img/logo.jpg?prop=srcSet') src=require('./img/logo.jpg?size=640'))
```
```html
<img srcset="/images/logo-320w.webp 320w, /images/logo-640w.webp 640w, /images/logo-960w.webp 960w" src="/images/logo-640w.webp">
```

### ❌ wrong usage
if the `responsive-loader` is configured in webpack for generate many images
```js
{
  test: /\.(gif|png|jpe?g|ico|svg|webp)$/i,
  use: {
    loader: 'responsive-loader',
    options: {
      name: 'img/[name].[hash:8]-[width]w.[ext]',
      format: 'webp',
      sizes: [320, 640, 960, 1200, 1800, 2400],
      adapter: require('responsive-loader/sharp')
    }
  }
}
```
and the resource request has't the query parameter `prop=PROPERTY_NAME`
```pug
img(src=require('./img/logo.jpg'))
```
then the `pug-plugin` doesn't understand what you want and returns comma separated list of all generated asset filenames only, without size, because a correct generated value know only self `responsive-loader`
```html
<img src="/images/logo-320w.webp,/images/logo-640w.webp,/images/logo-960w.webp">
```

P.S. can you please accept my PR and run this repo. It should build and start local in browser.

**Comment by myasarbardaklar** [comment] 2022-04-16 13:53
I accepted and i have a problem. When i make any change in scss files or pug files, it compiles lately. 4137ms it says. It wasnt like this before. Why is it like this now?

**Comment by webdiscus** [comment] 2022-04-16 14:09
> I accepted and i have a problem. When i make any change in scss files or pug files, it compiles lately. 4137ms it says. It wasnt like this before. Why is it like this now?

I research this problem now.

**Comment by myasarbardaklar** [comment] 2022-04-16 14:26
You are awesome! I hope i dont disturb or bother you.

**Comment by webdiscus** [comment] 2022-04-16 14:33
> You are awesome! I hope i dont disturb or bother you.

Don't worry, All is Ok :-)
Your usage case is very interest and can be useful for others.
I want to make the plugin as compatible as possible with other loaders.

**Comment by myasarbardaklar** [comment] 2022-04-16 14:39
Thank you so much :) I wait your answer for these problems. I have 2 client projects but I will not start any project until these problems get solved.

**Comment by webdiscus** [comment] 2022-04-16 17:25
can you please check the `npm run start` -> change some file -> rebuild
Whether by rebuild the entiries will be double processed, so one after the other?

By me local i have this confuse only with VSCode terminal. Same process in Idea is ok.

I have tested the repo with two versions `2.0.1` and `2.1.0-alpha.0` on my MacBook Pro 16 M1 Max.

### v2.0.1 'responsive-loader' is enabled  but not supported
- npm run build 3400ms
- npm run start 3750ms (first)
- npm run start 2380ms (rebuild after changes)

### 2.1.0-alpha.0 'responsive-loader' is enabled and works
- npm run build 3420ms
- npm run start 3800ms (first)
- npm run start 2300ms (rebuild after changes)

The build and rebuild time for all used resources is Ok.

If your see, no difference. I have changed the version of `pug-plugin` in `packages.json` -> `npm i`.

As it was before? Before, your repo didn't work at all.

**Comment by webdiscus** [comment] 2022-04-16 17:37
otherwise does the new alpha version work with 'responsive-loader'  in your project?

Performance tuning will happen after the stable release.
And I despair that x-times speed-up is still possible.

Next TODO: fix missing a required js file in pug, after rebuild (single build works fine).

**Comment by myasarbardaklar** [comment] 2022-04-16 22:49
I got same results with yours. But it wasnt like this before. I mean if i dont have responsive-loader package, building time was better and faster. If i make any change in any file, it was building faster. I'll wait your answer and stable release :)

**Comment by webdiscus** [comment] 2022-04-16 23:42
do you mean it was faster with version 1.5 or 2.0.1?
Which versions are you comparing?

**Comment by myasarbardaklar** [comment] 2022-04-17 09:39
It was faster with version 2.0.1.

**Comment by webdiscus** [comment] 2022-04-17 23:29
You has new PR with release version of pug-plugin:-)

I have released new version `2.1.0`:
- fixed all issues with HRM by webpack serv (Live Reload works for required JS only. HMR for pug and css is not supported yet --> manual reload the browser)
- x10 speed-up by rebuild

Note: see please changes in PR diff by webpack config.
The fast rebuild work in `render` method (pug-plugin option).
The `render` method is not compatible with `posthtml-loader` + `html-loader`.

Now the rebuild after changes take instead 2300ms --> 150-250ms.

**Comment by myasarbardaklar** [comment] 2022-04-18 10:30
Ah, so i cannot use posthtml-loader then? I use it for svg files to import. Is there a way for this you can suggest?

**Comment by webdiscus** [comment] 2022-04-18 10:40
> Ah, so i cannot use posthtml-loader then? I use it for svg files to import. Is there a way for this you can suggest?

You can use the `posthtml-loader`, but this loader require the `html` method for pug-loader and the additional `html-loader`.
If is used the `html-loader` then the rebuild after changes take x10 more time, same as first build. This is problem of `html-loader`, because he triggered rebuild all resources.

Also, 2 ways:

- fast rebuild, but without  `posthtml-loader`
- slow rebuild with  `posthtml-loader`


Did the plugin work before without the pug-loader options `method` together with `posthtml-loader`?

**Comment by webdiscus** [comment] 2022-04-18 10:45
How you use import of svg, in pug or in js?
Can you share please small example here.

**Comment by webdiscus** [comment] 2022-04-18 10:47
What do it - https://github.com/posthtml/posthtml-loader ?
In readme has't information about this plugin.

**Comment by myasarbardaklar** [comment] 2022-04-18 10:52
There is a plugin for svgs https://www.npmjs.com/package/posthtml-inline-svg. I use this one. And i also added inside webpack.common.js this "devServer: { devMiddleware: { writeToDisk: true } }". It works if I make any change in any file. It reloads the pages.

**Comment by webdiscus** [comment] 2022-04-18 11:40
> There is a plugin for svgs https://www.npmjs.com/package/posthtml-inline-svg. I use this one. And i also added inside webpack.common.js this "devServer: { devMiddleware: { writeToDisk: true } }". It works if I make any change in any file. It reloads the pages.

thank you for the tips with `devMiddleware`, it's really works :-)
For development I use `webpack watch` + `docker` to see results in real native app environment. I don't use live reload.

**Comment by myasarbardaklar** [comment] 2022-04-18 11:56
I have 4 questions if you dont mind.

1. Is there any solution for svg?

2. I might have svg files in src/img folder. But I might also have svg files in src/fonts. I wanna seperate them in build time. src/img svg files to dist/img, src/fonts to dist/fonts. Like this.

3. Is there any way to debug in pug file? For example when i require an image, i wanna debug it with console.log and i wanna see the results in terminal. But if your plugin's method is "render" or "compile", i cannot see the results in terminal.

4. If i have folder structure like this "src/img/banners" and if i require these images from "src/img/banners", can i have dist folder structure like this "dist/img/banners"? Or just "dist/img"? Because i can have kind of folder structures in src. Like "src/fonts/OpenSans/..." or "src/img/banners/...". I wanna have dist folder like this "dist/fonts/OpenSans/..." or "dist/img/banners/...".

Thank you sooo much! :)

**Comment by webdiscus** [comment] 2022-04-18 12:07
can you please answer whether the problems from subj (responsive-loader and HMR) is solved for you? Can I this issue to done?

Your questions I convert to separate issue.

**Comment by webdiscus** [comment] 2022-04-18 12:12
1. sorry, I don't know. I can only search in google.
2. + 4. -> converted in new issue
3. -> converted in new issue

**Comment by webdiscus** [comment] 2022-04-18 13:40
@myasarbardaklar,
see please the answer for 3. [here](https://github.com/webdiscus/pug-plugin/issues/10)

**Comment by webdiscus** [comment] 2022-04-18 14:07
@myasarbardaklar 

I have a tips for compatibility  with `responsive-loader` using before.
You can define an object in pug like the result object of `responsive-loader`:

```pug
mixin WImage(file)
    .w-img
        picture
            source(srcset=file.srcSet src=file.src type="image/webp")

-
  const imgFile = {
    src: require('../img/1033740.jpg?size=320'),
    srcSet: require('../img/1033740.jpg?prop=srcSet'),
  }

+WImage(imgFile)
```

**Comment by myasarbardaklar** [comment] 2022-04-18 20:44
Ah thank you so much. I've already done something like this :) But thanks anyway!

**Comment by webdiscus** [comment] 2022-04-26 21:57
> There is a plugin for svgs https://www.npmjs.com/package/posthtml-inline-svg. I use this one. And i also added inside webpack.common.js this "devServer: { devMiddleware: { writeToDisk: true } }". It works if I make any change in any file. It reloads the pages.

Hello @mybardaklar 

I found yet one cool method to live reload by a change any file, without write to disk:

```js
devServer: {
  static: {
    directory: path.join(__dirname, './dist')
  },

  watchFiles: {
    paths: ['src/**/*.*'], // <-- define glob path
    options: {
      usePolling: true,
    },
  },
},
```

**Comment by mybardaklar** [comment] 2022-04-27 03:16
Thank you so much for helping. But I made a kinda boilerplate with Gulp and Webpack. If you wanna check:
https://github.com/mybardaklar/gulp_static_boilerplate

**Comment by webdiscus** [comment] 2022-05-09 12:50
> 1. Is there any solution for svg?

Hello @mybardaklar,

in the new `2.3.0` version of pug plugin is added support for `inline SVG` and inline images (in HTML and in CSS). You not need mode any additional plugins to inline SVG in HTML.

Please see the usage example in demo app [Hello World](https://github.com/webdiscus/pug-plugin/tree/master/examples/hello-world).

Add to webpack config the following rule:
```js
       // inline images: png or svg icons with size < 4 KB only
        {
          test: /\.(png|svg)$/i,
          type: 'asset',
          include: /assets\/images/, // to ignore SVG from fonts directory
          exclude: /favicon/, // don't inline favicon
          parser: {
            dataUrlCondition: {
              maxSize: 4 * 1024, // define your max image size to inline in HTML/CSS
            },
          },
        },
```
See completely [webpack.config.js](https://github.com/webdiscus/pug-plugin/blob/master/examples/hello-world/webpack.config.js).

Pug:
```pug
img.logo(src=require('~Images/icons/webpack.svg'))
```
Generated HTML:
```html
<svg viewBox="0 0 200 200" class="logo">
  <path d="m600 0 530.3 300v600l-530.3 300-530.3-300v-600z" fill="#fff"></path>
  ...
</svg>
```

SCSS:
```scss
.webicon-mac-svg {
   background-image: url('~Images/icons/webicons/webicon-mac.svg');
}
```
Generated CSS:
```css
.webicon-mac-svg {
  background-image: url("data:image/svg+xml,<svg>...</svg>");
}
```
See completely [usage inline SVG in Pug](https://github.com/webdiscus/pug-plugin/blob/master/examples/hello-world/src/views/pages/home/index.pug).

**Comment by silveoj** [comment] 2022-06-06 16:11
@webdiscus
I read your messages how to combine `PugPlugin` and `responsive-loader`. It works.
But before it I use `responsive-loader` like:

webpack config - without `format` property
```javascript
        {
          test: /\.(gif|png|jpe?g|ico|svg|webp)$/i,
          type: 'asset/resource', // doesn't work without it - The reason: this file not found!
          include: [path.join(mySrcPath, "/assets/img")],
          use: {
            loader: "responsive-loader",
            options: {
              adapter: require("responsive-loader/sharp"),
              sizes: [100, 200, 300, 400],
              // format: "jpg", I don't use it
              outputPath: "assets/img",
              name: '[name]/[ext]/[name]-[width].[ext]',
            },
          },
        },
```

and pug file
```pug
-
  const myWebp1 = require('~Images/123.png?prop=width&format=webp');
  const myWebp2 = require('~Images/123.png?format=webp');
  const myWebpSize1 = require('~Images/123.png?sizes[]=100,sizes[]=200,sizes[]=300,sizes[]=400&format=webp'); // if no sizes property in config
```

It can be useful if I want convert only some images.
You can use this repository above https://github.com/webdiscus/pug-plugin/issues/8#issuecomment-1100031228

**Comment by silveoj** [comment] 2022-06-06 16:12
@webdiscus
I read your messages how to combine `PugPlugin` and `responsive-loader`. It works.
But before it I used `responsive-loader` like:

webpack config - without `format` property
```javascript
        {
          test: /\.(gif|png|jpe?g|ico|svg|webp)$/i,
          type: 'asset/resource', // doesn't work without it - The reason: this file not found!
          include: [path.join(mySrcPath, "/assets/img")],
          use: {
            loader: "responsive-loader",
            options: {
              adapter: require("responsive-loader/sharp"),
              sizes: [100, 200, 300, 400],
              // format: "jpg", I don't use it
              outputPath: "assets/img",
              name: '[name]/[ext]/[name]-[width].[ext]',
            },
          },
        },
```

and pug file
```pug
-
  const myWebp1 = require('~Images/123.png?prop=width&format=webp');
  const myWebp2 = require('~Images/123.png?format=webp');
  const myWebpSize1 = require('~Images/123.png?sizes[]=100,sizes[]=200,sizes[]=300,sizes[]=400&format=webp'); // if no sizes property in config
```

It can be useful if I want to convert only some images.
You can use this repository above https://github.com/webdiscus/pug-plugin/issues/8#issuecomment-1100031228

**Comment by silveoj** [comment] 2022-06-06 16:17
@webdiscus
I read your messages how to combine `PugPlugin` and `responsive-loader`. It works.
But before it I used `responsive-loader` like: (it doesn't work)

webpack config - without `format` property
```javascript
        {
          test: /\.(gif|png|jpe?g|ico|svg|webp)$/i,
          type: 'asset/resource', // doesn't work without it - The reason: this file not found!
          include: [path.join(mySrcPath, "/assets/img")],
          use: {
            loader: "responsive-loader",
            options: {
              adapter: require("responsive-loader/sharp"),
              sizes: [100, 200, 300, 400],
              // format: "jpg", I don't use it
              outputPath: "assets/img",
              name: '[name]/[ext]/[name]-[width].[ext]',
            },
          },
        },
```

and pug file
```pug
-
  const myWebp1 = require('~Images/123.png?prop=width&format=webp');
  const myWebp2 = require('~Images/123.png?format=webp');
  const myWebpSize1 = require('~Images/123.png?sizes[]=100,sizes[]=200,sizes[]=300,sizes[]=400&format=webp'); // if no sizes property in config
```

It can be useful if I want to convert only some images.
You can use this repository above https://github.com/webdiscus/pug-plugin/issues/8#issuecomment-1100031228

**Comment by webdiscus** [comment] 2022-06-06 17:02
@silveoj 
Thank you for very useful comment.
It was converted in the discussion [How to use PugPlugin and responsive-loader](https://github.com/webdiscus/pug-plugin/discussions/16).

P.S. after WWDC 2022 I make a working example with you suggestion :-)

**Comment by silveoj** [comment] 2022-06-07 17:10
Issue with scss
```scss
background-image: url('~Images/123.png')
```
It won't work if I use `sizes` and `format` in webpack config.

- With these properties `background-image` is not valid:
`url("/assets/img/123-300.jpg 1,/assets/img/123-600.jpg 1,/assets/img/123-658.jpg 1,/assets/img/123-300.webp 1,/assets/img/123-600.webp 1,/assets/img/123-658.webp 1")`
- Without these properties is valid: `url("/assets/img/123-658.png")`

I don't know how to add this support for PUG plugin with minimal code. I think it's better to each developer changes CSS individually,

1. Developers can use `background-image: -webkit-image-set(` https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set#providing_a_fallback
2. use `@support`  CSS rule.
3. Use different `rules` webpack config for CSS and HTML 
4. Or something else.

I will prepare example for the discussion topic.

**Comment by silveoj** [comment] 2022-06-07 17:11
Issue with scss
```scss
background-image: url('~Images/123.png')
```
It won't work if I use `sizes` and `format` in webpack config.

- With these properties `background-image` is not valid:
`url("/assets/img/123-300.jpg 1,/assets/img/123-600.jpg 1,/assets/img/123-658.jpg 1,/assets/img/123-300.webp 1,/assets/img/123-600.webp 1,/assets/img/123-658.webp 1")`
- Without these properties is valid: `url("/assets/img/123-658.png")`

I don't know how to add this support for PUG plugin with minimal code. I think it's better to each developer changes CSS individually,

1. Developers can use `background-image: -webkit-image-set(` https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set#providing_a_fallback
2. Use `@support`  CSS rule.
3. Use different `rules` webpack config for CSS and HTML - if possible
4. Or something else.

I will prepare example for the discussion topic.

**Comment by silveoj** [comment] 2022-06-09 15:11
In `responsive-loader` we can also use JSON5 notation
`<source srcSet={require('./image.jpg?{sizes:[50,100,200,300,400,500,600,700,800], format: "webp"}').srcSet} type='image/webp'/>`
Maybe it easier for you.

---
I found some working solutions for SCSS and HTML.

### webpack
```javascript
        {
          test: /\.(gif|png|jpe?g|webp)$/i,
          type: 'asset/resource', // doesn't work without it - The reason: this file not found!
          include: [path.join(mySrcPath, "/assets/img")],
          use: {
            loader: "responsive-loader",
            options: {
              adapter: require("responsive-loader/sharp"),
              sizes: [100, 200, 300, 400],
              // format: "jpg", // commented for SCSS
              outputPath: "assets/img",
              name: '[name]/[ext]/[name]-[width].[ext]',
            },
          },
        },
```

### SCSS
Now we get good url for SCSS.
For multiple formats we can use 2 `background-image` properties (desktop Chrome and Firefox load only last image)

```SCSS
    background-image: url('~Images/image.png?format=jpg');
    background-image: url('~Images/image.png?format=webp');
```

It's better to use `@supports`
```SCSS
    @supports (background-image: url('~Images/image.png?format=webp')) {
        background-image: url('~Images/image.png?format=webp');
    }
```
But we get `@supports (background-image: url("~Images/image.png?format=webp")) {`

### HTML
For HTML we need to use different order of params
  ```pug
  div width: #{require("~Images/image.png?prop=width&sizes[]=100,sizes[]=200,format=webp")}
  div height: #{require("~Images/image.png?prop=height&sizes[]=100,sizes[]=200,format=webp")}

  div srcSet webp: #{require("~Images/image.png?prop=srcSet&format=webp,sizes[]=100,sizes[]=200,sizes[]=300")}
  div srcSet jpg: doesn't work

  div src webp: #{require("~Images/image.png?prop=src&sizes[]=100,sizes[]=200,format=webp")}
  div src jpg: #{require("~Images/image.png?prop=src&sizes[]=100,sizes[]=200,format=jpg")}
  ```

 1.
- `prop=srcSet,format=jpg&sizes[]=100,sizes[]=200,sizes[]=800,sizes[]=900` ->` /assets/img/image/jpg/image-200.jpg 1,/assets/img/image/jpg/image-673.jpg 1` - not correct dimensions
- `prop=srcSet&format=webp,sizes[]=100,sizes[]=200,sizes[]=300` -> `/assets/img/image/webp/image-100.webp 100w,/assets/img/image/webp/image-200.webp 200w,/assets/img/image/webp/image-300.webp 300w` - correct dimensions but doesn't work for `jpg`.
2. Sometimes if `sizes` more than 2 -> I get different results - Can't repeat
3. Before my experiments I tried replace from `/assets/img/image/jpg/image-200.jpg` to `/assets/img/image/webp/image-200.webp`
- But `replace(/webp/g, 'jpg')` doesn't work -> I always get `webp`.
- If I `replace('assets', '')` - File not found

  Probable `require` returns me not string but ~NodeJS object: `"' + require('/assets/img/image.png?prop=src&{sizes:[100, 200, 300, 900], format: 'jpg'}') + '"`

**Comment by silveoj** [comment] 2022-06-09 15:12
@webdiscus 

In `responsive-loader` we can also use JSON5 notation
`<source srcSet={require('./image.jpg?{sizes:[50,100,200,300,400,500,600,700,800], format: "webp"}').srcSet} type='image/webp'/>`
Maybe it easier for you.

---
I found some working solutions for SCSS and HTML.

### webpack
comment `format` and you can don't comment `sizes`:
```javascript
        {
          test: /\.(gif|png|jpe?g|webp)$/i,
          type: 'asset/resource', // doesn't work without it - The reason: this file not found!
          include: [path.join(mySrcPath, "/assets/img")],
          use: {
            loader: "responsive-loader",
            options: {
              adapter: require("responsive-loader/sharp"),
              sizes: [100, 200, 300, 400],
              // format: "jpg", // commented for SCSS
              outputPath: "assets/img",
              name: '[name]/[ext]/[name]-[width].[ext]',
            },
          },
        },
```

### SCSS
Now we get good url for SCSS.
For multiple formats we can use 2 `background-image` properties (desktop Chrome and Firefox load only last image)

```SCSS
    background-image: url('~Images/image.png?format=jpg');
    background-image: url('~Images/image.png?format=webp');
```

It's better to use `@supports`
```SCSS
    @supports (background-image: url('~Images/image.png?format=webp')) {
        background-image: url('~Images/image.png?format=webp');
    }
```
But we get `@supports (background-image: url("~Images/image.png?format=webp")) {`

### HTML
For HTML we need to use different order of params
  ```pug
  div width: #{require("~Images/image.png?prop=width&sizes[]=100,sizes[]=200,format=webp")}
  div height: #{require("~Images/image.png?prop=height&sizes[]=100,sizes[]=200,format=webp")}

  div srcSet webp: #{require("~Images/image.png?prop=srcSet&format=webp,sizes[]=100,sizes[]=200,sizes[]=300")}
  div srcSet jpg: doesn't work

  div src webp: #{require("~Images/image.png?prop=src&sizes[]=100,sizes[]=200,format=webp")}
  div src jpg: #{require("~Images/image.png?prop=src&sizes[]=100,sizes[]=200,format=jpg")}
  ```

 1.
- `prop=srcSet,format=jpg&sizes[]=100,sizes[]=200,sizes[]=800,sizes[]=900` ->` /assets/img/image/jpg/image-200.jpg 1,/assets/img/image/jpg/image-673.jpg 1` - not correct dimensions
- `prop=srcSet&format=webp,sizes[]=100,sizes[]=200,sizes[]=300` -> `/assets/img/image/webp/image-100.webp 100w,/assets/img/image/webp/image-200.webp 200w,/assets/img/image/webp/image-300.webp 300w` - correct dimensions but doesn't work for `jpg`.
2. Sometimes if `sizes` more than 2 -> I get different results - Can't repeat
3. Before my experiments I tried replace from `/assets/img/image/jpg/image-200.jpg` to `/assets/img/image/webp/image-200.webp`
- But `replace(/webp/g, 'jpg')` doesn't work -> I always get `webp`.
- If I `replace('assets', '')` - File not found

  Probable `require` returns me not string but ~NodeJS object: `"' + require('/assets/img/image.png?prop=src&{sizes:[100, 200, 300, 900], format: 'jpg'}') + '"`

**Comment by webdiscus** [comment] 2022-06-09 15:21
@silveoj 

thank you for detail.
I know all this issues with query parameters. I'm just by the bug fixing. Today later or tomorrow I release the bugfix.

**Comment by webdiscus** [comment] 2022-06-09 15:36
@silveoj 

> In responsive-loader we can also use JSON5 notation
<source srcSet={require('./image.jpg?{sizes:[50,100,200,300,400,500,600,700,800], format: "webp"}').srcSet} type='image/webp'/>
Maybe it easier for you.

No, don't use JSON5 as query parameters, because it contains URI-reserved chars and using `html-loader` it occurs an parse ERROR.
See the standard [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986#section-2.2).

Before using of JSON5 query, it must be encoded.
The version `3.0.4` of `responsive-loader` can now decode the JSON5.
But default encode function `encodeURIComponent` not encoded chars reserved in RFC 3986.

Also, JSON5 query can be correctly encoded only with the function (copy&past 1:1 in your Pug):
```pug
- const fixedEncodeURIComponent = (str) => encodeURIComponent(str.replace(/[!'()*]/g, (c) => '%' + c.charCodeAt(0).toString(16)));
```

Then you can use it:

```pug
img(src=require('./image.jpeg?' + fixedEncodeURIComponent("{size:105, format: 'webp', placeholder: true}")))
```

It's works by me local in fixed beta version.

**Comment by silveoj** [comment] 2022-06-13 14:49
@webdiscus Thanks for updates.

I apply https://webdiscus.github.io/pug-plugin/responsive-image/ to my build.

```javascript
"pug-plugin": "^2.7.2",
"responsive-loader": "^3.0.4",
```

```javascript
{
    test: /\.(jpe?g|png|gif|webp)$/,
    type: 'asset/resource', // pugPlugin doesn't work without this line
    include: [path.join(dirSrc, "/assets/img")],
    use: {
      loader: "responsive-loader",
      options: {
        // adapter: require("responsive-loader/sharp"), // by default
        // sizes: [480, 640, 800, 1024, 2048],
        // format,
        outputPath: "assets/img",
        name: '[name]/[ext]/[name]-[width].[ext]', // assets/img/[name]/[ext]/[name]-[width].[ext] - the same
      },
    },
}
```

> Defaults, an image without queries will stay in its original size and format.

`require('~Images/image.png?format=jpg')` - without size - "The reason: this file not found!" error

`dist/assets/img` included correctly converted images (webp, jpg) but
- HTML generates hash names
- dist folder contains 5 hash png files (1 Kb each, can't open) (parallel with dist JS, CSS, HTML): `dist/13aebb007756697c0f96.png`
```HTML
<picture>
<source srcset="/d38c64dff32c9cca78b1.png?sizes[]=480,sizes[]=640,sizes[]=800,sizes[]=1024&amp;format=webp" type="image/webp">
<img src="/13aebb007756697c0f96.png?size=&amp;format=jpg" srcset="/8db8441da1cb4df16ac1.png?sizes[]=480,sizes[]=640,sizes[]=800,sizes[]=1024&amp;format=jpg" width="/c06720d9a0d04448662a.png?prop=width" height="/c06720d9a0d04448662a.png?prop=height" sizes="(min-width: 1024px) 1024px, 100vw" loading="lazy">
</picture>
```

**Comment by silveoj** [comment] 2022-06-14 00:27
@webdiscus 
I use NodeJS 14.17.0.
[repo](https://github.com/silveoj/pug-plugin-responsive-loader-issue)

**Comment by silveoj** [comment] 2022-06-14 00:29
@webdiscus [repo](https://github.com/silveoj/pug-plugin-responsive-loader-issue)

I use NodeJS 14.17.0.
See `result.png` with my `dist` folder.

**Comment by silveoj** [comment] 2022-06-14 00:37
@webdiscus [repo](https://github.com/silveoj/pug-plugin-responsive-loader-issue)

I use NodeJS 14.17.0.
See `result.png` with my `dist` folder.

**Comment by silveoj** [comment] 2022-06-14 11:45
@webdiscus [repo](https://github.com/silveoj/pug-plugin-responsive-loader-issue)

I use NodeJS 14.17.0 and 16.9.1
See `result.png` with my `dist` folder.

I tried `npm cache clean --force`; reinstall node_modules, 2 PCs - doesn't work.

**Comment by silveoj** [comment] 2022-06-14 11:45
@webdiscus [repo](https://github.com/silveoj/pug-plugin-responsive-loader-issue)

I use NodeJS 14.17.0 and 16.9.1
See `result.png` with my `dist` folder.

I tried `npm cache clean --force`; reinstalled node_modules, 2 PCs - doesn't work.

**Comment by silveoj** [comment] 2022-06-14 11:46
@webdiscus [repo](https://github.com/silveoj/pug-plugin-responsive-loader-issue)

I use NodeJS `14.17.0` and `16.9.1`
See `result.png` with my `dist` folder.

I tried `npm cache clean --force`; reinstalled `node_modules`, 2 PCs - doesn't work.

**Comment by webdiscus** [comment] 2022-06-14 17:16
@silveoj 

thanks for repo.

I use node v16.13.1 (npm v8.1.2) and your repo works by me local, w/o listed issues.

See please the comments:

```pug
 -
    const responsivePict = require('~Images/image.png?sizes[]=480,sizes[]=640,sizes[]=800,sizes[]=1024&format=webp');
    const responsiveImage = {
      srcSet: require('~Images/image.png?sizes[]=480,sizes[]=640,sizes[]=800,sizes[]=1024&format=jpg'),
      src: require('~Images/image.png?format=jpg'),
      width: require('~Images/image.png?prop=width'), <-- to get a width or height, not requires the format option
      height: require('~Images/image.png?prop=height'), <-- use the prop=height only
    };

  picture
    source(
-     srcSet=responsivePict.srcSet <-- the responsivePict it not an object
+     srcSet=responsivePict <-- the responsivePict contains already the sting with srcSet
      type='image/webp'
    )
    img(
      src=responsiveImage.src
      srcSet=responsiveImage.srcSet
      width=responsiveImage.width
      height=responsiveImage.height
    )
```

P.S. I will test your repo with node 14 and answer later.

**Comment by silveoj** [comment] 2022-06-15 02:08
@webdiscus I use Windows 10 (any NodeJS version; Python 3 is installed).
I have checked it in Linux -> it works.

I removed `pug-plugin` -> it doesn't work.

So I suppose it's `responsive-loader` issue.
I have created issue for `responsive-loader` https://github.com/dazuaz/responsive-loader/issues/157 with example without `pug-plugin`.

Thanks for quick replies.

**Comment by webdiscus** [comment] 2022-06-15 09:48
@silveoj 
I have tested on Win10 and I can reproduce the issue.
I found the problem in pug-plugin with a path in windows. I will fix it.

Please, close the issue for responsive-loader.

**Comment by webdiscus** [comment] 2022-06-15 10:40
@silveoj 

in version `2.7.3` is the issue fixed.
Thank you for the bug report!

**Comment by silveoj** [comment] 2022-06-15 18:53
Thanks.

Found small issue with CSS
`background-image: `
- `url('~Images/image.png?size=&format=jpg');` - works
- `url('~Images/image.png?format=jpg')` - doesn't work

Any combinations with png/webp are correct.

**Comment by webdiscus** [comment] 2022-06-15 20:52
@silveoj 

this is the bug when used same file with same format in both Pug and SCSS.
I try to fix it.
Thank you for bug report.

**Closed** 2022-06-16 14:40 UTC
Labels: bug, enhancement
