### ISSUE TITLE
Alias resolving issue on Windows

### ISSUE THREAD

**Issue by JONMARSHALDEV** [webdiscus/pug-plugin#23] opened 2022-06-22 06:57 UTC
using latest webpack, ang pug-plugin
can't resolve alises usage like in example
try to use "extends ~Views/layouts/default.pug"
in "views/pages/home/index.pug"

got error:
`ERROR in ./src/views/pages/home/index.pug
Module build failed (from ./node_modules/@webdiscus/pug-loader/src/index.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error)
[pug-loader] Pug compilation failed.
PugLoaderException:
[pug-loader] the file ~Views/layouts/default.pug can't be resolved in the pug template:
D:\0html\pug_plugin_test2\src\views\pages\home\index.pug
Error: Can't resolve '~Views/layouts/default.pug' in 'D:\0html\pug_plugin_test2\src\views\pages\home'
    at D:\0html\pug_plugin_test2\src\views\pages\home\index.pug line 2
    at processResult (D:\0html\pug_plugin_test2\node_modules\webpack\lib\NormalModule.js:755:12)
    at D:\0html\pug_plugin_test2\node_modules\webpack\lib\NormalModule.js:860:5
    at D:\0html\pug_plugin_test2\node_modules\loader-runner\lib\LoaderRunner.js:400:11
    at D:\0html\pug_plugin_test2\node_modules\loader-runner\lib\LoaderRunner.js:252:18
    at context.callback (D:\0html\pug_plugin_test2\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at D:\0html\pug_plugin_test2\node_modules\@webdiscus\pug-loader\src\index.js:270:21
    at Object.compile (D:\0html\pug_plugin_test2\node_modules\@webdiscus\pug-loader\src\index.js:256:5)
    at Object.module.exports (D:\0html\pug_plugin_test2\node_modules\@webdiscus\pug-loader\src\index.js:269:11)`

it seems it try to find "pug for extending" in same directory.
if specify directly "extends ../../layouts/default.pug" it works.
instead of it, aliases for "~Images", "~Styles" work properly.

use Windows 10 x64.

**Comment by webdiscus** [comment] 2022-06-22 21:54
Hello @JONMARSHALDEV,

thanks for the bug report.
The issue is fixed in the version  `2.7.7`.

**Closed** 2022-06-23 10:57 UTC
Labels: bug
